[package]
name = "zkp2p-fps0-host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
serde = {version = "1.0", features = ["derive"]}
risc0-zkvm = { version = "=0.19.1" }

[features]
metal = [ "risc0-zkvm/metal" ]